sudo: required
language: generic 
services: 
    - docker

before_install:
    - docker build -t paolapo/docker-example -f ./client/Dockerfile.dev ./client
        

after_success:
    - docker build -t paolapo/example-client ./client
    - docker build -t paolapo/example-nginx ./nginx  
    - docker build -t paolapo/example-server ./server 
    - docker build -t paolapo/example-worker ./worker
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
    
    - docker push paolapo/example-client
    - docker push paolapo/example-nginx
    - docker push paolapo/example-server
    - docker push paolapo/example-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region:  us-east-2
    app: docker-simple
    env: DockerSimple-env
    bucket_name: elasticbeanstalk-us-east-2-111577139685
    bucket_path: docker-simple
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY    